# Generated by Django 4.2.2 on 2023-06-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentCompany', models.TextField(verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Блоки страницы о компании',
                'verbose_name_plural': 'Страница о компании',
            },
        ),
    ]
