# Generated by Django 4.2.2 on 2023-06-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewsBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameuser', models.CharField(max_length=20, verbose_name='Имя')),
                ('reviews', models.TextField(max_length=230, verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AlterModelOptions(
            name='companypages',
            options={'verbose_name': 'Блоки страницы о компании', 'verbose_name_plural': 'Блок о компании'},
        ),
    ]
