# Generated by Django 4.2.2 on 2023-06-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_formmodal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=80, verbose_name='Адрес')),
                ('hours', models.CharField(max_length=40, verbose_name='Режим работы')),
                ('phone', models.CharField(max_length=25, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контактные данные',
            },
        ),
    ]
