# Generated by Django 4.2.2 on 2023-06-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90, verbose_name='Название услуги')),
                ('serv_item1', models.CharField(max_length=120, verbose_name='Описание услуги')),
                ('serv_item2', models.CharField(max_length=120, verbose_name='Описание услуги')),
                ('serv_item3', models.CharField(max_length=120, verbose_name='Описание услуги')),
                ('serv_item4', models.CharField(max_length=120, verbose_name='Описание услуги')),
                ('serv_item5', models.CharField(max_length=120, verbose_name='Описание услуги')),
                ('serv_item6', models.CharField(max_length=120, verbose_name='Описание услуги')),
                ('serv_item7', models.CharField(max_length=120, verbose_name='Описание услуги')),
                ('serv_item8', models.CharField(max_length=120, verbose_name='Описание услуги')),
                ('serv_item9', models.CharField(max_length=120, verbose_name='Описание услуги')),
            ],
        ),
    ]
